name:                hsscripts
version:             0.1.0.0
github:              "dcastro/hsscripts"
license:             BSD3
author:              "Diogo Castro"
maintainer:          "dc@diogocastro.com"
copyright:           "2017 Diogo Castro"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on Github at <https://github.com/githubuser/hsscripts#readme>

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src
  dependencies:
    - Cabal
    - text
    - yaml
    - process
    - bytestring
    - unordered-containers
    - filepath
    - aeson
    - vector
executables:
  hsscripts-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - hsscripts

tests:
  hsscripts-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - hsscripts
